# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

use_frameworks!
workspace 'gameappsubmissionmodules'

target 'gameappsubmission' do

end

target 'Core' do
  project '../Core/Core'
end

target 'Search' do
  project '../Search/Search'
end

target 'Favorite' do
  project '../Favorite/Favorite'
end
